**Modified Chicken Game**

In [ ]:
# install the tools you will use later
!pip install --upgrade setuptools
!pip install --upgrade pip
!pip install nashpy
!pip install quantecon

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.8/214.8 kB 5.3 MB/s eta 0:00:00


The game is based on a classical game in game theory literature, Chicken Game, which is a model of conflict between risk-taking and risk-avoidance of two players. One of the classical game scenarios is when two drivers drive toward each other, each can choose to swerve or straight. If one of them chooses to swerve and the other chooses to straight, the former one will be seen as chickening out and will receive a lower payoff (2), while the latter one will receive a higher payoff (7) since he is braver. If both choose to swerve, it will be a tie, and both receive a moderate payoff (6,6). While, if both players choose to straight, they will crash into each other, and receives a zero payoff, since they fail to avoid the risk. In the modified version, one additional rule is that both players can choose whether to spy at the beginning of the game, if so, he will pay 1 payoff at last. The game has two rounds, and the total payoff is the sum of the payoff in two rounds.

Case 1: Neither player choose to use spies.

In [ ]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[0, 7],
        [2, 6]]) # A is the row player

B = np.array([[0, 2],
        [7, 6]]) # B is the column player
     

In [ ]:
# Form the game
game2 = nash.Game(A,B)
game2

Bi matrix game with payoff matrices:

Row player:
[[0 7]
 [2 6]]

Column player:
[[0 2]
 [7 6]]

In [ ]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))


In this case, there are three Nash equilibriums:

1.Player A swerves, and Player B goes straight. In this case, the payoff is 2 and 7.

2.Player A goes straight and player B swerves. In this case, the payoff is 7 or 2.

In both equilibrium, for the player who chooses straight, the expectation is 1/2x(0+7)=3.5, for the player who chooses swerve, the expectation is 1/2x(2+6)=4. Because the expectation for choosing swerve is higher, both player tend to choose swerve if they are rational.

3.This is a mixed strategies. Player A and player B swerves with probability 1/3 and goes straight with probability 2/3

In this equlibrium, the expectation for both player is 1/3x1/2x(2+6)+2/3x1/2x(0+7)=3, which is even lower than the pure strategies. 

Case 2: Both players choose to use spies.

In [ ]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[-1, 6],
        [1, 5]]) # A is the row player

B = np.array([[-1, 1],
        [6, 5]]) # B is the column player

In [ ]:
# Form the game
game2 = nash.Game(A,B)
game2

Bi matrix game with payoff matrices:

Row player:
[[-1  6]
 [ 1  5]]

Column player:
[[-1  1]
 [ 6  5]]

In [ ]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))


In this case, there are three Nash equilibriums:

1.Player A swerves, and Player B goes straight. In this case, the payoff is 2 and 7.

2.Player A goes straight and player B swerves. In this case, the payoff is 7 or 2.

In both equilibrium, for the player who chooses straight, the expectation is 1/2x(-1+6)=2.5, for the player who chooses swerve, the expectation is 1/2x(1+5)=3. Because the expectation for choosing swerve is higher, both player tend to choose swerve if they are rational.

3.This is a mixed strategies. Player A and player B swerves with probability 1/3 and goes straight with probability 2/3.

In this equlibrium, the expectation for both player is 1/3x1/2x(1+5)+2/3x1/2x(-1+6)=2.67, which is even lower than the pure strategies. 

Case 3: One players choose to use spies.

In [9]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[-1, 6],
        [1, 5]]) # A is the row player

B = np.array([[0, 2],
        [7, 6]]) # B is the column player

In [10]:
# Form the game
game2 = nash.Game(A,B)
game2

Bi matrix game with payoff matrices:

Row player:
[[-1  6]
 [ 1  5]]

Column player:
[[0 2]
 [7 6]]

In [12]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))


In this case, there are three Nash equilibriums:

1.Player A swerves, and Player B goes straight. In this case, the payoff is 2 and 7.

2.Player A goes straight and player B swerves. In this case, the payoff is 7 or 2.

3.This is a mixed strategy. Player A and player B swerve with probability 1/3 and go straight with probability 2/3.

However, in this case, Nash Equilibrium cannot be true in real-word situations. Because if one player uses spies, and he knows his opponent will chooses swerve, he must choose straight to maximize his own payoff. Meanwhile, if the opponent knows that the player uses spies, he may choose straight to retaliate this distrust behavior. Therefore, the equilibrium is unstable.